# Autogenerated by devscripts/update-version.py

__version__ = '2026.07.05'

RELEASE_GIT_HEAD = 'b7ea21e5638e306db6bca8bfb79c2911b77c48be'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'

ORIGIN = 'KernFerm/yt-dlp'

_pkg_version = '2026.07.05'
