# Autogenerated by devscripts/update-version.py

__version__ = '2026.08.16'

RELEASE_GIT_HEAD = '15ca8ea81f6e5a216ac1e500fdb1f3817ac48c1c'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'

ORIGIN = 'KernFerm/yt-dlp'

_pkg_version = '2026.08.16'
