# Autogenerated by devscripts/update-version.py

__version__ = '2026.07.06'

RELEASE_GIT_HEAD = '741331b44668abb7f6d88ae90280eaa64d2ad0f2'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'

ORIGIN = 'KernFerm/yt-dlp'

_pkg_version = '2026.07.06'
